language: cpp
env:
  global:
  - app_id=inputstream.hls
  
# https://github.com/headmelted/vscode/blob/a57e613e9e7d2fdb3917502cb98bbd1eaef8c058/.travis.yml
# amd64 toolchain (used as a base for non-sudo compilation, which is faster) 
include: &toolchain_amd64
  sudo: false
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-6
        - g++-6-multilib
        
# OSX amd64 toolchain
include: &toolchain_osx_amd64
  <<: *toolchain_amd64
  env:
    - LABEL=amd64_osx
    - ARCH=amd64
    - GPP_COMPILER=g++
    - GCC_COMPILER=gcc
        
# linux amd64 toolchain
include: &toolchain_linux_amd64
  <<: *toolchain_amd64
  env:
    - LABEL=amd64_linux
    - ARCH=amd64
    - GPP_COMPILER=g++-6
    - GCC_COMPILER=gcc-6
        
# cross toolchain (used as a base for multiarch cross-compilation configurations below) 
include: &toolchain_linux_cross
  dist: trusty
  sudo: required # for dpkg --add-architecture locking
  
# armhf toolchain
include: &toolchain_linux_armhf
  <<: *toolchain_linux_cross
  env:
    - LABEL=armhf_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=armhf
    - GNU_TRIPLET=arm-linux-gnueabihf
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=arm-linux-gnueabihf-g++
    - GCC_COMPILER=arm-linux-gnueabihf-gcc
  
# arm64 toolchain
include: &toolchain_linux_arm64
  <<: *toolchain_linux_cross
  env:
    - LABEL=arm64_linux
    - CROSS_TOOLCHAIN=true
    - ARCH=arm64
    - GNU_TRIPLET=aarch64-linux-gnu
    - GNU_MULTILIB_TRIPLET=arm-linux-gnueabihf
    - GPP_COMPILER=aarch64-linux-gnu-g++
    - GCC_COMPILER=aarch64-linux-gnu-gcc

matrix:
  include:
  - os: osx
    <<: *toolchain_osx_amd64
  - os: linux
    <<: *toolchain_linux_amd64
  - os: linux
    <<: *toolchain_linux_armhf
  - os: linux
    <<: *toolchain_linux_arm64

before_install:
  - export CXX="${GPP_COMPILER}" CC="${GCC_COMPILER}";
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew update        ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then which cmake || brew install cmake ; fi
  - if [[ "${CROSS_TOOLCHAIN}" == "true" ]]; then
      sudo rm -rf /etc/apt/sources.list.d/**;
      sudo rm /etc/apt/sources.list; 
      echo "deb [arch=amd64,i386] http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee /etc/apt/sources.list;
      echo "deb [arch=${ARCH}] http://ports.ubuntu.com/ubuntu-ports xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list;
      echo "deb-src http://archive.ubuntu.com/ubuntu xenial main universe multiverse restricted" | sudo tee -a /etc/apt/sources.list;
      sudo dpkg --add-architecture ${ARCH};
      sudo apt-get update -yq;
      sudo apt-get install -y gcc-${GNU_TRIPLET} g++-${GNU_TRIPLET} pkg-config-${GNU_TRIPLET} crossbuild-essential-${ARCH} g++-multilib-${GNU_MULTILIB_TRIPLET} gcc-multilib-${GNU_MULTILIB_TRIPLET} dpkg-dev libgcc1 libgcc1:${ARCH} libc6 libc6:${ARCH} libc6-dev:${ARCH} 
    fi

before_script:
- cd $TRAVIS_BUILD_DIR/..
- git clone --depth=1 https://github.com/xbmc/xbmc.git -b Krypton
- cp -R ${app_id}/kodi/ $TRAVIS_BUILD_DIR/../xbmc/project/cmake/addons/addons/
- cd ${app_id} && mkdir build && cd build
- cmake -DADDONS_TO_BUILD=${app_id} -DADDON_SRC_PREFIX=$TRAVIS_BUILD_DIR/.. -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/../xbmc/addons -DPACKAGE_ZIP=1 -DPACKAGE_DIR="$TRAVIS_BUILD_DIR/zips" $TRAVIS_BUILD_DIR/../xbmc/project/cmake/addons
script: make package-addons
before_deploy:
- cd "$TRAVIS_BUILD_DIR/zips" 
- mv ${app_id}-*.zip "${app_id}-$TRAVIS_OS_NAME.zip"
deploy:
  provider: releases
  api_key:
    secure: gVWe3kNqk27tKkBK6ddu+OU3riLU/PFYrEHUaPhkMPc2WLd7z/E1YHi49IOLukIw15tWOR/qghJOeP/xY9C2zugGo9rwmybyvWrIPAzqljeBz0e3KtmJn6LbXYoPz0HY9ezV4Qvtcm5eHgWkLD1yAsh7w8HLiDDRSpT8o0BYyqEvwD+j1MJnpTNJFr4G+z8raMmUxoVvF20we9HMHhaQxm0zf6I83eY7sIdEwIC90GU5bXXLrw0iGNkG/YVodJi49rBtXD6c6w/OfK9iRDMhJpZpiiplEWHbfOSQS4iSYkRdFGQiu6DcgWg8IFVwR+IoCAu/9vhcZu2QZ3QeCRMhYC19JgpWKNC7dhyXHRxcjFXWsRPgIdNHmUoDmrorfzvYDhoqnNThyiEyFzHlP9HaIrJtwRiMBDgb9DlzIv98OqkMeVpKsE6L2cufhHZyqHgXvyfmPbctyBRJE5CFoPOfbwtqVfT253f5g6PkWXkKw7am42pWnpRzojrnHvuZlHYBnqa6sdBx6tMjHH+Lu4amVWeZ/RAvfd9G4PTvMC0HJgvAhJPqX0RS57hwo1UWPEYLkLIXcRdDda2LGvq9tnvWy7nmaYG11IczXfFgs6PrjJ0wXiwXBtx58WWyftgiDhX5ebcbKA7Z+XANe52Hl5EXFkWc1t6TMSaUvPhEyw5uYPA=
  file: "$TRAVIS_BUILD_DIR/zips/${app_id}-$TRAVIS_OS_NAME.zip"
  skip_cleanup: true
  on:
    repo: awaters1/inputstream.hls
    tags: true
